name: Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    name: Build SDK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build SDK
        run: yarn build

      - name: Build example app
        run: cd example && yarn install && yarn build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist
            !dist/**/*.map
